/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.poly.demo.view;

import com.poly.demo.controller.PolyCafeController;

/**
 *
 * @author hangnt
 */
public class PolyCafeJFrame extends javax.swing.JFrame implements PolyCafeController{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PolyCafeJFrame.class.getName());

    /**
     * Creates new form PolyCafeJFrame
     */
    public PolyCafeJFrame() {
        initComponents();
        // chay wellcome 
        this.showWelcomeJDialog(this);
        // chay login 
        this.showLoginJDialog(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTop = new javax.swing.JPanel();
        panelBotom = new javax.swing.JPanel();
        panelRight = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTop.setBackground(new java.awt.Color(153, 255, 102));

        javax.swing.GroupLayout panelTopLayout = new javax.swing.GroupLayout(panelTop);
        panelTop.setLayout(panelTopLayout);
        panelTopLayout.setHorizontalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        panelTopLayout.setVerticalGroup(
            panelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(panelTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 301, -1));

        panelBotom.setBackground(new java.awt.Color(255, 255, 0));

        javax.swing.GroupLayout panelBotomLayout = new javax.swing.GroupLayout(panelBotom);
        panelBotom.setLayout(panelBotomLayout);
        panelBotomLayout.setHorizontalGroup(
            panelBotomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );
        panelBotomLayout.setVerticalGroup(
            panelBotomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );

        getContentPane().add(panelBotom, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, -1, -1));

        panelRight.setBackground(new java.awt.Color(255, 51, 51));
        panelRight.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Loại đồ uống");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        panelRight.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 130, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/coffee-shop.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        panelRight.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 446, 429));

        getContentPane().add(panelRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 0, -1, 435));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       this.showCategoryJDialog(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PolyCafeJFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panelBotom;
    private javax.swing.JPanel panelRight;
    private javax.swing.JPanel panelTop;
    // End of variables declaration//GEN-END:variables
}
